# Overrides for the production environment.
logLevel: warn
regions:
  cn:
    apiBaseUrl: https://cn-api.svc.plus
    authUrl: https://cn-accounts.svc.plus
    dashboardUrl: https://cn-console.svc.plus
  global:
    apiBaseUrl: https://global-api.svc.plus
    authUrl: https://global-accounts.svc.plus
    dashboardUrl: https://global-console.svc.plus
